config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # root "articles#index"
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  resources :vehicles do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[index show update]
  resources :businesses, only: %i[index new create show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
end

app/models/business.rb
class Business < ApplicationRecord
  has_many :vehicles
  belongs_to :user
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :business
  has_many :bookings
  has_many :vehicles, through: :business
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  include PgSearch::Model
  has_many :bookings
  belongs_to :business
  has_many_attached :photos

  pg_search_scope :search_by_model_and_driver_name,
    against: [ :model, :driver_name ],
    using: {
      tsearch: { prefix: true }
    };

  validates :photos, length: { minimum: 3, message: "Please upload at least 3 photos" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # We need @vehicle in our `simple_form_for`
  before_action :set_vehicle, only: %i[new create]

  def index
    @bookings = Booking.where(user_id: current_user.id) # customer
    @requests = Booking.where(vehicle: current_user.vehicles) # business owner
  end

  def new
    # set_vehicle
    @booking = Booking.new
  end

  def create
    # set_vehicle
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.vehicle_id = @vehicle.id
    @booking.total_price = @vehicle.base_price * (@booking.end_date - @booking.start_date).to_i
    @booking.status = "Pending"
    @booking.save
    redirect_to booking_path(@booking)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.status = params[:status]
    @booking.save
    redirect_to bookings_path
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def index
    @businesses = Business.all
    # The `geocoded` scope filters only busineses with coordinates
    @markers = @businesses.geocoded.map do |business|
      {
        lat: business.latitude,
        lng: business.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {business: business}),
        marker_html: render_to_string(partial: "marker")
      }
    end
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    @business.user_id = current_user.id
    if @business.save
      redirect_to business_path(@business)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @business = Business.find(params[:id])
  end

  private

  def business_params
    params.require(:business).permit(:organisation_name, :tax_number, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_vehicle, only: %i[show edit update destroy]

  def index
    @vehicles = Vehicle.all
    if params[:query].present?
      sql_subquery = <<~SQL
        vehicles.model @@ :query
        OR vehicles.category @@ :query
      SQL
      @vehicles = @vehicles.where(sql_subquery, query: params[:query])
    end
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.business_id = current_user.business.id
    if @vehicle.save
      redirect_to vehicle_path(@vehicle)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @vehicle.update(vehicle_params)
      redirect_to vehicle_path(@vehicle)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @vehicle.destroy
    redirect_to vehicles_path, status: :see_other
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:model, :category, :driver_name, :base_price, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="full-page">
  <div class="container-custom">
    <div class="d-flex align-items-center justify-content-center">
    <h1>
      Hey
      <strong style="color: orange"><%= current_user.first_name.capitalize %></strong>
      <strong style="color: orange"><%= current_user.last_name.capitalize %></strong>
    </h1>
    </div>
    <div class="d-flex align-items-center justify-content-center">
    <h1>
      Find all your bookings below!
    </h1>
    </div>
  </div>

  <div class="container">
    <% unless current_user.business.present? %>
      <!-- code to execute if user doesn't have a business -->
      <table class="table table-hover vertical-align-middle">
        <caption>You have a total of <%= @bookings.count %> bookings.</caption>
        <thead class="thead-dark">
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Category</th>
            <th scope="col">Model</th>
            <th scope="col">Driver</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Total Price</th>
            <th scope="col">Status</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each do |booking| %>
          <% count = 0 %>
            <tr>
              <th scope="row"><%= booking.id %></th>
              <td><%= booking.vehicle.category %></td>
              <td><%= booking.vehicle.model %></td>
              <td><%= booking.vehicle.driver_name %></td>
              <td><%= booking.start_date %></td>
              <td><%= booking.end_date %></td>
              <td><%= booking.total_price %> $</td>
              <td><%= booking.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <% else %>
        <table class="table table-hover vertical-align-middle">
          <caption>You have a total of <%= @requests.count %> requests.</caption>
          <thead class="thead-dark">
            <tr>

              <th scope="col">Id</th>
              <th scope="col">Category</th>
              <th scope="col">Model</th>
              <th scope="col">Driver</th>
              <th scope="col">Start Date</th>
              <th scope="col">End Date</th>
              <th scope="col">Total Price</th>
              <th scope="col">Status</th>
              <th scope="col">Approval</th>
            </tr>
          </thead>
          <tbody>
            <% @requests.each do |request| %>
            <% count = 0 %>
              <tr>
                <th scope="row"><%= request.id %></th>
                <td><%= request.vehicle.category %></td>
                <td><%= request.vehicle.model %></td>
                <td><%= request.vehicle.driver_name %></td>
                <td><%= request.start_date %></td>
                <td><%= request.end_date %></td>
                <td><%= request.total_price %> $</td>
                <td><%= request.status %></td>
                <td>
                  <% if request.status.downcase == "pending" %>
                    <div class="d-flex align-center justify-content-center">
                      <%=
                      button_to "Accept", booking_path(request.id, status: "Accepted"), method: :patch, class: "button-secondary-accept"
                      %>
                      <%=
                        button_to "Decline", booking_path(request.id, status: "Declined"), method: :patch, class: "button-secondary-decline"
                      %>
                    </div>
                  <% else %>
                    <p class="completed-button">Done</p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="full-page">
  <div class="form-info my-4">
    <div class="d-flex align-items-center justify-content-center my-3">
      <h1>Create a new booking</h1>
    </div>

    <hr>

    <%= simple_form_for [@vehicle, @booking] do |f| %>
      <div class="d-flex justify-content-center">
        <%= f.input :start_date, as: :date, html5: true %>
        <%= f.input :end_date, as: :date, html5: true  %>
      </div>
      <div class="d-flex align-items-center justify-content-center my-3">
      <%= f.submit "Submit booking", class: "button-primary" %>
      </div>
    <% end %>

    <div class="d-flex align-items-center justify-content-end">
      <p><%= link_to "Cancel booking", vehicle_path(@vehicle) %></p>
    </div>

  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="container">
    <div class="text-center justify-content-center my-3">
      <h1>
        Thank you
        <strong style="color: orange"><%= @booking.user.first_name %></strong>
        <strong style="color: orange"><%= @booking.user.last_name %></strong>
        for riding with us!
      </h1>
      <p>Your request has been correctly submitted and payment information accepted. </p><br>
      <p><strong>Here are your booking details:</strong></p>
    </div>

    <hr>
  </div>
  <div class="container">
    <div class=booking-page-image>
      <%= image_tag(cl_image_path(@booking.vehicle.photos.first.key), class: "main-car myImg", style: "border-radius: 5px") %>
    </div>
  </div>

  <div class="container my-5">
    <div class="booking-card">
      <ul>
        <li>Your vehicle will be a
        <a href="<%= vehicle_path(@booking.vehicle) %>" id="vehicle-link">
          <strong style="color: orange">
          <%= @booking.vehicle.category %>
          <%= @booking.vehicle.model %>
          </strong> </a> driven by
        <strong style="color: orange"><%= @booking.vehicle.driver_name %></strong>.
        </li>
        <li>Start Date: <strong style="color: orange"><%= @booking.start_date %></strong>.</li>
        <li>End Date: <strong style="color: orange"><%= @booking.end_date %></strong>.</li>
        <li>Total Price: <strong style="color: orange">$<%= @booking.total_price %></strong> for <strong style="color: orange"><%= (@booking.end_date - @booking.start_date).to_i %></strong> days.</li>
        <li>Status: <strong style="color: orange"><%= @booking.status %></strong>.</li>
      </ul>
    </div>

    <div class="text-center justify-content-center my-3">
      <p>You will be notified via email once your driver accepts your booking.</p><br>
      <p>We hope you enjoy your ride and look forward to serving you again in the future! </p>
    </div>

    <div class="d-flex align-items-center justify-content-center">
      <p><%= link_to "See all vehicles", vehicles_path, class: "button-primary-bookings" %></p>
    </div>
  </div>
</div>

app/views/businesses/_info_window.html.erb
<h2 class="popup-header"><%= business.organisation_name %></h2>
<p><%= business.address %></p>

app/views/businesses/_map_form.html.erb
<%= f.input :address,
  input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
%>

app/views/businesses/_marker.html.erb
<%= image_tag "marker.png", height: 30, width: 30, alt: "marker" %>

app/views/businesses/index.html.erb
<div class="full-height">
<div style="width: 70%; height: 800px;"
  class="text-center my-5 mx-auto"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/businesses/new.html.erb
<div class="container my-4">
  <div class="form-info">
    <div class="d-flex align-items-center justify-content-center my-3">
    <h1>Create a new business</h1>
    </div>

    <hr>

    <%= simple_form_for [@business] do |f| %>
      <%= f.input :organisation_name, input_html: { class: "w-100" } %>
      <%= f.input :tax_number, input_html: { class: "w-100" } %>
      <%= f.input :address, input_html: { class: "w-100" } %>
      <div class="d-flex align-items-center justify-content-center my-3">
        <%= f.submit "Create", class: "button-primary" %>
      </div>
    <% end %>

    <div class="d-flex align-items-center justify-content-center">
      <p><%= link_to "Cancel creation", root_path %></p>
    </div>

  </div>
</div>

app/views/businesses/show.html.erb
<div class="full-page">
  <div class="container">
    <div class="text-center justify-content-center my-3">
      <h1>
        Thank you
        <strong style="color: orange"><%= @business.user.first_name %></strong>
        <strong style="color: orange"><%= @business.user.last_name %></strong>
        for partnering with us!
      </h1>
      <p>Congratulations! Your company profile has been successfully created and you can now submit your first vehicles.</p><br>
      <p>If you don't see your vehicles immediately on our platform, please don't worry.</p><br>
      <p>Our team performs regular checks to ensure that our partners comply with our security and quality guidelines.</p><br>
      <p><strong>Here are your company details:</strong></p>
    </div>
  </div>

  <div class="container">
    <div class="booking-card">
      <ul>
        <li>Organisation Name: <strong style="color: orange"><%= @business.organisation_name %></strong>.</li>
        <li>Tax Number: <strong style="color: orange"><%= @business.tax_number %></strong>.</li>
        <li>Tax Number: <strong style="color: orange"><%= @business.address %></strong>.</li>
      </ul>
    </div>
    <div class="text-center justify-content-center my-3">
      <p>We are excited to collaborate with you and look forward to serving our customers together!</p>
    </div>
  </div>

  <div class="d-flex align-items-center justify-content-center">
    <p><%= link_to "Submit first vehicle", new_vehicle_path %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LOC8TE</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80);">
  <div class="d-flex align-items-center justify-content-center">
    <h1><span class="auto-type"></span></h1>

    <script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>

    <script>
      var typed = new Typed(".auto-type", {
          strings: ["Get around on your own terms"],
          typeSpeed: 150,
          backSpeed: 150,
          loop: true
      });
    </script>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <h2>LOC8TE your perfect vehicle for the day or week!</h2>
  </div>
  <div class="d-flex align-items-center justify-content-center">
    <p>We are here to provide businesses and users a platform to hire a vehicle and driver to take the stress out of LOC8TING transport for the day<p>
  </div>
</div>

<div class="container">
  <div class="container text-center my-3">
    <h2>Choose from our selection of vehicles</h2>
    <hr>
      <div class="row mx-auto my-auto justify-content-center">
          <div id="recipeCarousel" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner" role="listbox">
                  <div class="carousel-item active">
                      <div class="col-md-3">
                          <div class="card">
                              <div class="card-img">
                                  <img src="https://images.unsplash.com/photo-1661281812258-129793403c61?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1172&q=80" class="img-fluid">
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="carousel-item">
                      <div class="col-md-3">
                          <div class="card">
                              <div class="card-img">
                                  <img src="https://blog-media.lifepal.co.id/app/uploads/sites/3/2021/08/16165057/Toyota-Alphard.jpg" class="img-fluid">
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="carousel-item">
                      <div class="col-md-3">
                          <div class="card">
                              <div class="card-img">
                                  <img src="https://images.unsplash.com/photo-1546933751-22670568bacf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80" class="img-fluid">
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="carousel-item">
                      <div class="col-md-3">
                          <div class="card">
                              <div class="card-img">
                                  <img src="https://images.unsplash.com/photo-1542362567-b07e54358753?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80" class="img-fluid">
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="carousel-item">
                      <div class="col-md-3">
                          <div class="card">
                              <div class="card-img">
                                  <img src="https://www.pensketruckrental.com/media-library/penske-heavy-duty-truck-driving-over-bridge.jpg?id=31291376&width=1245&height=700&quality=85&coordinates=370%2C579%2C1103%2C520" class="img-fluid">
                              </div>
                          </div>
                      </div>
                  </div>
                  <div class="carousel-item">
                      <div class="col-md-3">
                          <div class="card">
                              <div class="card-img">
                                  <img src="https://cdn.motor1.com/images/mgl/8Qv7P/s3/volkner-mobil-performance---trequarti-anteriore-garage-aperto.webp" class="img-fluid">
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <a class="carousel-control-prev bg-transparent w-aut" href="#recipeCarousel" role="button" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              </a>
              <a class="carousel-control-next bg-transparent w-aut" href="#recipeCarousel" role="button" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
              </a>
          </div>
      </div>
  </div>



  <div class="d-flex align-items-center justify-content-center my-3">
    <%= link_to "View all", vehicles_path, class: "button-primary"%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="notice-alert" class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div id="alert-alert" class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
  </div>
<% end %>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    var noticeAlert = $('#notice-alert');
    if (noticeAlert.length) {
      setTimeout(function() {
        noticeAlert.fadeOut();
      }, 2000);
    }

    var alertAlert = $('#alert-alert');
    if (alertAlert.length) {
      setTimeout(function() {
        alertAlert.fadeOut();
      }, 2000);
    }
  });
</script>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="copyright">
    @2023LOC8TE.Ltd
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="logo">
  <%= link_to root_path do %>
    <%= image_tag "logo-white.png", alt: "Logo", class:"logo" %>
  <% end %>
  </div>
    <div class="navbar">
      <ul class="nav-links">
        <li>
        <%= link_to root_path %>
        <% if user_signed_in? && current_user.business.nil? %>
          <%= link_to "Register your Business", new_business_path, class:"nav-links"%>
        <% end %>
        </li>
        <li>
        <% link_to root_path %>
        <% if user_signed_in? && current_user.business.present? %>
          <%= link_to "Submit a Vehicle", new_vehicle_path, class:"nav-links"%>
        <% end %>
        </li>
        <li>
        <%= link_to root_path %>
        <% if user_signed_in? %>
          <%= link_to "My bookings", bookings_path, class:"nav-links"%>
        <% end %>
        </li>
        <li>
        <%= link_to "Vehicles", vehicles_path, class:"nav-links"%>
        </li>
      </ul>

      <div class="nav-divider my-3"></div>
      <% if user_signed_in? %>
        <%=link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:"button-primary"%>
      <% else %>
        <%= link_to "/users/sign_in", class: "button-primary" do %>
        Log in
        <% end %>
      <% end %>
    </div>
</div>

app/views/vehicles/edit.html.erb
<h1>Edit Vehicle</h1>

<%= simple_form_for [@vehicle] do |f| %>
  <%= f.input :model %>
  <%= f.input :category %>
  <%= f.input :driver_name %>
  <%= f.input :base_price %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit "Edit", class: "btn btn-primary" %>
<% end %>

<p><%= link_to "Go back to vehicle", vehicles_path(@vehicle) %></p>
<p><%= link_to "See all vehicles", vehicles_path %></p>

app/views/vehicles/index.html.erb
<div class="d-flex align-items-center justify-content-center my-3">
  <h1>Vehicles Currently Available</h1>
</div>

<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: vehicles_path, method: :get, class: "d-flex justify-content-center" do %>
      <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Search a vehicle "
      %>
      <%= submit_tag "Search", name: "", class: "button-primary" %>
    <% end %>
  </div>
</div>

  <div class="row justify-content-center my-3">
    <div class="col-sm-12">
      <div id="vehicles">
        <% if @vehicles.any? %>
          <div class="cards">
    <% @vehicles.each do |vehicle| %>
        <div class="cards-container">
        <% if vehicle.photos.attached? %>
          <a href="<%= vehicle_path(vehicle) %>">
           <div class="card-category" style="background-image: url('<%= cl_image_path(vehicle.photos.first.key) %>')">
           </div>
          </a>
          <% else %>
            <div class="card-category" style="background-image: url('https://images.unsplash.com/photo-1622893288761-823ba60f17a6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1856&q=80')">
          </div>
          <% end %>
          <li>
          <div class="card-description my-2">
            <h2><%= link_to vehicle.model.titleize, vehicle_path(vehicle), class:"text-decoration-none text-black" %></h2>
          </div>

          <div class="card-description d-flex">
            <p><%= vehicle.category.upcase %></p>
          </div>

          <div class="card-description">
            <p><b>Starting Price </b></p> <h2>$<%= vehicle.base_price %></h2>
          </div>
          </li>
        </div>
    <% end %>
  </div>
        <% else %>
          <em>Sorry, no vehicles found.</em>
        <% end %>
      </div>
    </div>
  </div>

app/views/vehicles/new.html.erb
<div class="container my-4">
  <div class="form-info">
    <div class="d-flex align-items-center justify-content-center my-3">
    <h1>Submit your vehicle</h1>
    </div>

    <hr>

    <%= simple_form_for [@vehicle] do |f| %>
      <%= f.input :model, input_html: { class: "w-100" } %>
      <%= f.input :category, input_html: { class: "w-100" } %>
      <%= f.input :driver_name, input_html: { class: "w-100" } %>
      <%= f.input :base_price, input_html: { class: "w-100" } %>
      <%= f.input :photos, as: :file, input_html: { multiple: true, class: "w-100" } %>
      <div class="d-flex align-items-center justify-content-center my-3">
        <%= f.submit "Create", class: "button-primary" %>
      </div>
    <% end %>
    <div class="d-flex align-items-center justify-content-center">
      <p><%= link_to "See all vehicles", vehicles_path %></p>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<div class="container my-3">
  <div class="container">
    <div class="row">
      <div class="col-8">
        <%= image_tag(cl_image_path(@vehicle.photos.first.key), class: "main-car myImg") %>
      </div>
      <div class="col-4">
        <%= image_tag(cl_image_path(@vehicle.photos.second.key), class: "top-car") %>
          <%= image_tag(cl_image_path(@vehicle.photos.third.key), class: "bottom-car") %>
      </div>
    </div>
  </div>

  <hr>

  <h3> Find below all the information about this vehicle </h3>
  <p>
    This <strong style="color: orange"><%= @vehicle.model.titleize %></strong> is offered for rent by <strong style="color: orange"><%= @vehicle.business.organisation_name %></strong>
  </p>
  <div class="d-flex align-items-center justify-content-between">
    <div class="d-flex flex-row align-items-center">
      <i class="fa-solid fa-car" style="color: $dark-blue"></i>
      <span>Category: <strong style="color: orange"><%= @vehicle.category %></strong></span>
    </div>
    <div class="d-flex align-items-center justify-content-between">
      <i class="fa-solid fa-id-card" style="color: $dark-blue"></i>
      <span>  Driver: <strong style="color: orange"><%= @vehicle.driver_name %></strong></span>
    </div>
    <div class="d-flex align-items-center justify-content-between">
      <i class="fa-solid fa-money-bill" style="color: $dark-blue"></i>
      <span>  Price: <strong style="color: orange"><%= @vehicle.base_price%></strong></span>
    </div>
  </div>

  <hr>

  <div class="d-flex align-items-center justify-content-between mt-3 mb-3">
    <%= link_to "See all vehicles", vehicles_path, class: "button-primary" %>
    <%= link_to "Book now", new_vehicle_booking_path(@vehicle), class: "button-primary" %>
    <%= link_to "Delete vehicle",
      vehicle_path(@vehicle),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
      class: "button-primary"
    %>
  </div>

</div>